### ISSUE TITLE
Error install as local user

### ISSUE THREAD

**Issue by fleixi** [Disane87/docudigger#1009]
I try to install docudigger as local user not global on an arch-linux and get this error:

`npm install @disane-dev/docudigger
`
```
0 verbose cli /usr/bin/node /usr/bin/npm
1 info using npm@10.8.1
2 info using node@v22.4.0
3 silly config load:file:/usr/lib/node_modules/npm/npmrc
4 silly config load:file:/home/fleixi/.npmrc
5 silly config load:file:/etc/npmrc
6 verbose title npm install @disane-dev/docudigger
7 verbose argv "install" "@disane-dev/docudigger"
8 verbose logfile logs-max:10 dir:/home/fleixi/.npm/_logs/2024-08-17T10_56_27_335Z-
9 verbose logfile /home/fleixi/.npm/_logs/2024-08-17T10_56_27_335Z-debug-0.log
10 silly packumentCache heap:4345298944 maxSize:1086324736 maxEntrySize:543162368
11 silly logfile start cleaning logs, removing 1 files
12 silly logfile done cleaning log files
13 silly idealTree buildDeps
14 silly fetch manifest @disane-dev/docudigger@*
15 silly packumentCache full:https://registry.npmjs.org/@disane-dev%2fdocudigger cache-miss
16 http fetch GET 200 https://registry.npmjs.org/@disane-dev%2fdocudigger 1275ms (cache revalidated)
17 silly packumentCache full:https://registry.npmjs.org/@disane-dev%2fdocudigger set size:647389 disposed:false
18 silly placeDep ROOT @disane-dev/docudigger@2.0.6 OK for:  want: *
19 silly fetch manifest luxon@^3.4.4
20 silly packumentCache full:https://registry.npmjs.org/luxon cache-miss
21 silly fetch manifest winston@^3.13.0
22 silly packumentCache full:https://registry.npmjs.org/winston cache-miss
23 silly fetch manifest node-cron@^3.0.3
24 silly packumentCache full:https://registry.npmjs.org/node-cron cache-miss
25 silly fetch manifest puppeteer@^22.10.0
26 silly packumentCache full:https://registry.npmjs.org/puppeteer cache-miss
27 silly fetch manifest @oclif/core@^3.26.6
28 silly packumentCache full:https://registry.npmjs.org/@oclif%2fcore cache-miss
29 silly fetch manifest @oclif/plugin-help@^6.0.22
30 silly packumentCache full:https://registry.npmjs.org/@oclif%2fplugin-help cache-miss
31 silly fetch manifest @oclif/plugin-plugins@^5.1.3
32 silly packumentCache full:https://registry.npmjs.org/@oclif%2fplugin-plugins cache-miss
33 silly fetch manifest @oclif/plugin-commands@^3.3.4
34 silly packumentCache full:https://registry.npmjs.org/@oclif%2fplugin-commands cache-miss
35 http fetch GET 200 https://registry.npmjs.org/node-cron 87ms (cache revalidated)
36 silly packumentCache full:https://registry.npmjs.org/node-cron set size:55280 disposed:false
37 http fetch GET 200 https://registry.npmjs.org/luxon 134ms (cache revalidated)
38 silly packumentCache full:https://registry.npmjs.org/luxon set size:491356 disposed:false
39 http fetch GET 200 https://registry.npmjs.org/puppeteer 158ms (cache revalidated)
40 silly packumentCache full:https://registry.npmjs.org/puppeteer set size:3639917 disposed:false
41 http fetch GET 200 https://registry.npmjs.org/winston 192ms (cache revalidated)
42 silly packumentCache full:https://registry.npmjs.org/winston set size:252477 disposed:false
43 http fetch GET 200 https://registry.npmjs.org/@oclif%2fplugin-help 213ms (cache revalidated)
44 silly packumentCache full:https://registry.npmjs.org/@oclif%2fplugin-help set size:515354 disposed:false
45 http fetch GET 200 https://registry.npmjs.org/@oclif%2fcore 228ms (cache revalidated)
46 silly packumentCache full:https://registry.npmjs.org/@oclif%2fcore set size:1712920 disposed:false
47 http fetch GET 200 https://registry.npmjs.org/@oclif%2fplugin-plugins 250ms (cache revalidated)
48 silly packumentCache full:https://registry.npmjs.org/@oclif%2fplugin-plugins set size:1001131 disposed:false
49 http fetch GET 200 https://registry.npmjs.org/@oclif%2fplugin-commands 255ms (cache revalidated)
50 silly packumentCache full:https://registry.npmjs.org/@oclif%2fplugin-commands set size:252262 disposed:false
51 silly reify moves {}
52 warn deprecated @types/winston@2.4.4: This is a stub types definition. winston provides its own type definitions, so you do not need this installed.
53 warn deprecated @types/puppeteer@7.0.4: This is a stub types definition. puppeteer provides its own type definitions, so you do not need this installed.
54 warn deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read https://babeljs.io/env to update!
55 warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
56 warn deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
57 warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
58 warn deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
59 info run yarn@1.22.22 preinstall node_modules/@disane-dev/docudigger/node_modules/yarn :; (node ./preinstall.js > /dev/null 2>&1 || true)
60 info run yarn@1.22.22 preinstall { code: 0, signal: null }
61 info run @disane-dev/docudigger@2.0.6 postinstall node_modules/@disane-dev/docudigger ts-node ./scripts/postinstall.ts
62 info run core-js@2.6.12 postinstall node_modules/@disane-dev/docudigger/node_modules/core-js node -e "try{require('./postinstall')}catch(e){}"
63 info run puppeteer@22.10.0 postinstall node_modules/@disane-dev/docudigger/node_modules/puppeteer node install.mjs
64 info run core-js@2.6.12 postinstall { code: 0, signal: null }
65 info run @disane-dev/docudigger@2.0.6 postinstall { code: 1, signal: null }
66 info run puppeteer@22.10.0 postinstall { code: 0, signal: null }
67 verbose stack Error: command failed
67 verbose stack     at promiseSpawn (/usr/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:22:22)
67 verbose stack     at spawnWithShell (/usr/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:124:10)
67 verbose stack     at promiseSpawn (/usr/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:12:12)
67 verbose stack     at runScriptPkg (/usr/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/run-script-pkg.js:77:13)
67 verbose stack     at runScript (/usr/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/run-script.js:9:12)
67 verbose stack     at /usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/rebuild.js:329:17
67 verbose stack     at run (/usr/lib/node_modules/npm/node_modules/promise-call-limit/dist/commonjs/index.js:67:22)
67 verbose stack     at /usr/lib/node_modules/npm/node_modules/promise-call-limit/dist/commonjs/index.js:84:9
67 verbose stack     at new Promise (<anonymous>)
67 verbose stack     at callLimit (/usr/lib/node_modules/npm/node_modules/promise-call-limit/dist/commonjs/index.js:35:69)
68 verbose pkgid @disane-dev/docudigger@2.0.6
69 error code 1
70 error path /home/fleixi/node_modules/@disane-dev/docudigger
71 error command failed
72 error command sh -c ts-node ./scripts/postinstall.ts
73 error node:internal/modules/cjs/loader:1222
73 error   throw err;
73 error   ^
73 error
73 error Error: Cannot find module './postinstall.ts'
73 error Require stack:
73 error - /home/fleixi/node_modules/@disane-dev/docudigger/scripts/imaginaryUncacheableRequireResolveScript
73 error     at Module._resolveFilename (node:internal/modules/cjs/loader:1219:15)
73 error     at Function.resolve (node:internal/modules/helpers:133:19)
73 error     at requireResolveNonCached (/home/fleixi/node_modules/@disane-dev/docudigger/node_modules/ts-node/dist/bin.js:549:16)
73 error     at getProjectSearchDir (/home/fleixi/node_modules/@disane-dev/docudigger/node_modules/ts-node/dist/bin.js:519:40)
73 error     at phase3 (/home/fleixi/node_modules/@disane-dev/docudigger/node_modules/ts-node/dist/bin.js:267:27)
73 error     at bootstrap (/home/fleixi/node_modules/@disane-dev/docudigger/node_modules/ts-node/dist/bin.js:47:30)
73 error     at main (/home/fleixi/node_modules/@disane-dev/docudigger/node_modules/ts-node/dist/bin.js:33:12)
73 error     at Object.<anonymous> (/home/fleixi/node_modules/@disane-dev/docudigger/node_modules/ts-node/dist/bin.js:579:5)
73 error     at Module._compile (node:internal/modules/cjs/loader:1467:14)
73 error     at Module._extensions..js (node:internal/modules/cjs/loader:1551:10) {
73 error   code: 'MODULE_NOT_FOUND',
73 error   requireStack: [
73 error     '/home/fleixi/node_modules/@disane-dev/docudigger/scripts/imaginaryUncacheableRequireResolveScript'
73 error   ]
73 error }
73 error
73 error Node.js v22.4.0
74 silly unfinished npm timer reify 1723892187518
75 silly unfinished npm timer reify:build 1723892195579
76 silly unfinished npm timer build 1723892195581
77 silly unfinished npm timer build:deps 1723892195582
78 silly unfinished npm timer build:run:postinstall 1723892195669
79 silly unfinished npm timer build:run:postinstall:node_modules/@disane-dev/docudigger 1723892195669
80 verbose cwd /home/fleixi
81 verbose os Linux 6.9.7-arch1-1
82 verbose node v22.4.0
83 verbose npm  v10.8.1
84 verbose exit 1
85 verbose code 1
```

**Comment by Disane87** [comment]
If you want to use it locally please tzry to use `npm install @disane-dev/docudigger --ignore-scripts`

currently I have the dev scripts in the package.json when building which is false. But currently I don't have any time to fix this unfortunatly :(

**Comment by Disane87** [comment]
@fleixi Did the `npm install @disane-dev/docudigger --ignore-scripts` work for you?
