### ISSUE TITLE
⚠️ Docker images are broken - help needed

### ISSUE THREAD

**Issue by Disane87** [Disane87/docudigger#1136]
It seems the docker images are broken in the current `dev`. The release docker image throws some exceptions:
> docudigger-1  | [0] [error] [2024-10-30 09:10:42] [scrape:amazon]:      unhandledRejection: Could not find Chrome (ver. 127.0.6533.88). This can occur if either
docudigger-1  | [0]  1. you did not perform an installation before running the script (e.g. `npx puppeteer browsers install chrome`) or
docudigger-1  | [0]  2. your cache path is incorrectly configured (which is: /home/node/.cache/puppeteer).
docudigger-1  | [0] For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
docudigger-1  | [0] Error: Could not find Chrome (ver. 127.0.6533.88). This can occur if either
docudigger-1  | [0]  1. you did not perform an installation before running the script (e.g. `npx puppeteer browsers install chrome`) or
docudigger-1  | [0]  2. your cache path is incorrectly configured (which is: /home/node/.cache/puppeteer).
docudigger-1  | [0] For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
docudigger-1  | [0]     at ChromeLauncher.resolveExecutablePath (/home/node/.npm-global/lib/node_modules/@disane-dev/docudigger/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:291:27)
docudigger-1  | [0]     at ChromeLauncher.executablePath (/home/node/.npm-global/lib/node_modules/@disane-dev/docudigger/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:209:25)
docudigger-1  | [0]     at ChromeLauncher.computeLaunchArguments (/home/node/.npm-global/lib/node_modules/@disane-dev/docudigger/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:89:37)
docudigger-1  | [0]     at async ChromeLauncher.launch (/home/node/.npm-global/lib/node_modules/@disane-dev/docudigger/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:70:28)
docudigger-1  | [0]     at async Puppeteer.setup (/home/node/.npm-global/lib/node_modules/@disane-dev/docudigger/dist/classes/puppeteer.class.js:16:24)
docudigger-1  | [0]     at async Amazon.init (/home/node/.npm-global/lib/node_modules/@disane-dev/docudigger/dist/classes/scrape-command.class.js:36:24)
docudigger-1  | [0]     at async Amazon._run (/home/node/.npm-global/lib/node_modules/@disane-dev/docudigger/node_modules/@oclif/core/lib/command.js:301:13)
docudigger-1  | [0]     at async Config.runCommand (/home/node/.npm-global/lib/node_modules/@disane-dev/docudigger/node_modules/@oclif/core/lib/config/config.js:425:25)
docudigger-1  | [0]     at async Object.run (/home/node/.npm-global/lib/node_modules/@disane-dev/docudigger/node_modules/@oclif/core/lib/main.js:95:16)
docudigger-1  | [0] docudigger scrape amazon exited with code 1

Thats pretty weird, because the `npx puppeteer browsers install chrome` is already been used:
https://github.com/Disane87/docudigger/blob/31479d47f7e6a41633cd4203643bc953acf8c0f2/dockerfile#L41

The debug docker file works flawlessly:
https://github.com/Disane87/docudigger/blob/31479d47f7e6a41633cd4203643bc953acf8c0f2/dockerfile.debug#L1-L17

The main difference between them is that the debug dockerfile doesnt use:
- ARG/ENV because they are set by the vscode task when running the debug image
- The published NPM package, instead it uses the plain projects which is copied into the image

Somebody got a clue why this isn't working with the `production` dockerfile?

**Comment by Disane87** [comment]
It seems this issue occured because of the transition to a new puppeteer version. The debug dockerfile uses the fixed version of puppeteer of the `package.json` but the production dockerfile not.

**Comment by maxkostas** [comment]
Hello!

It seems that on dev.13 the docker image is working again! Great work!

I wanted it to have a full run going, but for some reasons, it does not properly start processing?

Here is the log output:

```
[+] Running 1/0
 ✔ Container amazon-docudigger-1  Created                                                                                      0.0s
Attaching to docudigger-1
docudigger-1  | [0] (node:15) Warning: SyntaxError
docudigger-1  | [0] module: @oclif/core@4.0.31
docudigger-1  | [0] task: findCommand (scrape:all.d)
docudigger-1  | [0] plugin: @disane-dev/docudigger
docudigger-1  | [0] root: /home/node/.npm-global/lib/node_modules/@disane-dev/docudigger
docudigger-1  | [0] message: Cannot use import statement outside a module
docudigger-1  | [0] See more details with DEBUG=*
docudigger-1  | [0] (Use `node --trace-warnings ...` to show where the warning was created)
docudigger-1  | [0] (node:15) Warning: SyntaxError
docudigger-1  | [0] module: @oclif/core@4.0.31
docudigger-1  | [0] task: findCommand (scrape:amazon:index.d)
docudigger-1  | [0] plugin: @disane-dev/docudigger
docudigger-1  | [0] root: /home/node/.npm-global/lib/node_modules/@disane-dev/docudigger
docudigger-1  | [0] message: Cannot use import statement outside a module
docudigger-1  | [0] See more details with DEBUG=*
docudigger-1  | [0] [info] [2024-10-31 10:10:24] [scrape:all]:  runAll
docudigger-1  | [0] Platform:  linux
docudigger-1  | [0] [info] [2024-10-31 10:10:24] [scrape:amazon]:       OnlyNew activated.
docudigger-1  | [0] [info] [2024-10-31 10:10:24] [scrape:amazon]:       Getting last run
docudigger-1  | [0] [warn] [2024-10-31 10:10:24] [scrape:amazon]:       process.json not found. Full run needed. OnlyNew deactivated.
docudigger-1  | [0] [info] [2024-10-31 10:10:24] [scrape:amazon]:       Getting last run. Got: undefined
docudigger-1  | [0] [info] [2024-10-31 10:10:24] [scrape:amazon]:       No latest scrape found. Processing all years and pages.
docudigger-1  | [0] [info] [2024-10-31 10:10:29] [scrape:amazon]:       Logged in
docudigger-1  | [0] [info] [2024-10-31 10:10:32] [scrape:amazon]:       Year filter undefined. Getting all possible years
docudigger-1  | [0] [info] [2024-10-31 10:10:32] [scrape:amazon]:       First possible year: undefined
docudigger-1  | [0] [info] [2024-10-31 10:10:32] [scrape:amazon]:       Last possible year: undefined
docudigger-1  | [0] [info] [2024-10-31 10:10:32] [scrape:amazon]:       Processing years
docudigger-1  | [0] [info] [2024-10-31 10:10:33] [scrape:amazon]:       Recurring activated. Not terminating. Waiting for next run.
docudigger-1  | [0] docudigger scrape all exited with code 0
docudigger-1 exited with code 0
```


Here is the docker file:

```
name: amazon
services:
    docudigger:
        environment:
            - AMAZON_USERNAME=XXXX
            - AMAZON_PASSWORD=XXXX
            - AMAZON_TLD=de
            - AMAZON_YEAR_FILTER=2024
            - AMAZON_PAGE_FILTER=1
        volumes:
            - C:/Users/XXXX/test:/home/node/docudigger
        image: ghcr.io/disane87/docudigger:2.0.6-dev.13
volumes:
    C:
        external: true
        name: C
```

It strange because I do have a year filter active.

**Comment by Disane87** [comment]
Please set the env variable `LOG_LEVEL=debug` and send me the entire log of that run :)

**Comment by maxkostas** [comment]
Of course! Here you go:

```
 ✔ Container amazon-docudigger-1  Recreated                                                                                    0.1s
Attaching to docudigger-1
docudigger-1  | [0] (node:15) Warning: SyntaxError
docudigger-1  | [0] module: @oclif/core@4.0.31
docudigger-1  | [0] task: findCommand (scrape:all.d)
docudigger-1  | [0] plugin: @disane-dev/docudigger
docudigger-1  | [0] root: /home/node/.npm-global/lib/node_modules/@disane-dev/docudigger
docudigger-1  | [0] message: Cannot use import statement outside a module
docudigger-1  | [0] See more details with DEBUG=*
docudigger-1  | [0] (Use `node --trace-warnings ...` to show where the warning was created)
docudigger-1  | [0] (node:15) Warning: SyntaxError
docudigger-1  | [0] module: @oclif/core@4.0.31
docudigger-1  | [0] task: findCommand (scrape:amazon:index.d)
docudigger-1  | [0] plugin: @disane-dev/docudigger
docudigger-1  | [0] root: /home/node/.npm-global/lib/node_modules/@disane-dev/docudigger
docudigger-1  | [0] message: Cannot use import statement outside a module
docudigger-1  | [0] See more details with DEBUG=*
docudigger-1  | [0] [debug] [2024-10-31 10:10:07] [scrape:all]:         Command scrape:all initialized
docudigger-1  | [0] [debug] [2024-10-31 10:10:07] [scrape:all]:         Flags: {"logLevel":"debug","debug":true,"logPath":"logs","recurring":true,"recurringCron":"*/30 * * * *"}
docudigger-1  | [0] [info] [2024-10-31 10:10:07] [scrape:all]:  runAll
docudigger-1  | [0] [debug] [2024-10-31 10:10:07] [scrape:amazon]:      Command scrape:amazon initialized
docudigger-1  | [0] [debug] [2024-10-31 10:10:07] [scrape:amazon]:      Flags: {"logLevel":"debug","debug":true,"logPath":"logs","recurring":true,"recurringCron":"*/30 * * * *","fileDestinationFolder":"data","fileFallbackExentension":".pdf","onlyNew":true,"username":"XXXXXX","password":"XXXXX","tld":"de","yearFilter":2024,"pageFilter":1}
docudigger-1  | [0] [debug] [2024-10-31 10:10:07] [scrape:amazon]:      processJsonFile: /home/node/docudigger/data/process.json
docudigger-1  | [0] [debug] [2024-10-31 10:10:07] [scrape:amazon]:      fileDestinationFolder: data
docudigger-1  | [0] [debug] [2024-10-31 10:10:07] [scrape:amazon]:      Running in Docker: true
docudigger-1  | [0] Platform:  linux
docudigger-1  | [0] [info] [2024-10-31 10:10:08] [scrape:amazon]:       OnlyNew activated.
docudigger-1  | [0] [info] [2024-10-31 10:10:08] [scrape:amazon]:       Getting last run
docudigger-1  | [0] [warn] [2024-10-31 10:10:08] [scrape:amazon]:       process.json not found. Full run needed. OnlyNew deactivated.
docudigger-1  | [0] [info] [2024-10-31 10:10:08] [scrape:amazon]:       Getting last run. Got: undefined
docudigger-1  | [0] [info] [2024-10-31 10:10:08] [scrape:amazon]:       No latest scrape found. Processing all years and pages.
docudigger-1  | [0] [debug] [2024-10-31 10:10:08] [scrape:amazon]:      Options: {
docudigger-1  | [0]     "logLevel": "debug",
docudigger-1  | [0]     "debug": true,
docudigger-1  | [0]     "logPath": "logs",
docudigger-1  | [0]     "recurring": true,
docudigger-1  | [0]     "recurringCron": "*/30 * * * *",
docudigger-1  | [0]     "fileDestinationFolder": "data",
docudigger-1  | [0]     "fileFallbackExentension": ".pdf",
docudigger-1  | [0]     "onlyNew": false,
docudigger-1  | [0]     "username": "XXXXXX",
docudigger-1  | [0]     "password": "XXXXX",
docudigger-1  | [0]     "tld": "de"
docudigger-1  | [0] }
docudigger-1  | [0] [debug] [2024-10-31 10:10:08] [scrape:amazon]:      Getting selectors...
docudigger-1  | [0] [debug] [2024-10-31 10:10:08] [scrape:amazon]:      Selectors: {
docudigger-1  | [0]     "orderCards": "div.order.js-order-card",
docudigger-1  | [0]     "invoiceSpans": "span.hide-if-no-js .a-declarative[data-action=\"a-popover\"]",
docudigger-1  | [0]     "orderNr": ".yohtmlc-order-id span:nth-last-child(1) bdi",
docudigger-1  | [0]     "orderDate": ".a-column .a-row:nth-last-child(1) span",
docudigger-1  | [0]     "popover": "#a-popover-content-{{index}}",
docudigger-1  | [0]     "invoiceList": "ul.invoice-list",
docudigger-1  | [0]     "invoiceLinks": "a[href*=\"invoice.pdf\"]",
docudigger-1  | [0]     "pagination": "ul.a-pagination li.a-normal:nth-last-child(2) a",
docudigger-1  | [0]     "yearFilter": "select[name=\"orderFilter\"]#orderFilter",
docudigger-1  | [0]     "authError": "#auth-error-message-box .a-unordered-list li",
docudigger-1  | [0]     "authWarning": "#auth-warning-message-box .a-unordered-list li",
docudigger-1  | [0]     "captchaImage": "div.cvf-captcha-img img[alt~=\"captcha\"]"
docudigger-1  | [0] }
docudigger-1  | [0] [info] [2024-10-31 10:10:13] [scrape:amazon]:       Logged in
docudigger-1  | [0] [debug] [2024-10-31 10:10:14] [scrape:amazon]:      Page language: de-de
docudigger-1  | [0] [debug] [2024-10-31 10:10:14] [scrape:amazon]:      Going to order page...
docudigger-1  | [0] [debug] [2024-10-31 10:10:14] [scrape:amazon]:      Going to year... 2024 order page 0
docudigger-1  | [0] [debug] [2024-10-31 10:10:16] [scrape:amazon]:      Getting possible years...
docudigger-1  | [0] [info] [2024-10-31 10:10:16] [scrape:amazon]:       Year filter undefined. Getting all possible years
docudigger-1  | [0] [debug] [2024-10-31 10:10:17] [scrape:amazon]:      Checking possible years. Got
docudigger-1  | [0] [info] [2024-10-31 10:10:17] [scrape:amazon]:       First possible year: undefined
docudigger-1  | [0] [info] [2024-10-31 10:10:17] [scrape:amazon]:       Last possible year: undefined
docudigger-1  | [0] [info] [2024-10-31 10:10:17] [scrape:amazon]:       Processing years
docudigger-1  | [0] [info] [2024-10-31 10:10:17] [scrape:amazon]:       Recurring activated. Not terminating. Waiting for next run.
docudigger-1  | [0] docudigger scrape all exited with code 0
```

with this docker:

```
name: amazon
services:
    docudigger:
        environment:
            - AMAZON_USERNAME=XXXXX
            - AMAZON_PASSWORD=XXXXX
            - AMAZON_TLD=de
            - AMAZON_YEAR_FILTER=2024
            - AMAZON_PAGE_FILTER=1
            - LOG_LEVEL=debug
        volumes:
            - C:/Users/XXXX/test:/home/node/docudigger
        image: ghcr.io/disane87/docudigger:2.0.6-dev.13
volumes:
    C:
        external: true
        name: C

```
