### ISSUE TITLE
node engine compatibility should be updated

### ISSUE THREAD

**Issue by ayelder** [Disane87/docudigger#1266]
When trying to run npm install, I end up getting the following error

ERR! command sh -c node install.mjs
npm ERR! file:///home/drew/workspace/docudigger/node_modules/puppeteer/install.mjs:34
npm ERR!   const {downloadBrowsers} = await importInstaller();
npm ERR!                              ^^^^^
npm ERR! 
npm ERR! SyntaxError: Unexpected reserved word
npm ERR!     at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
npm ERR!     at async link (internal/modules/esm/module_job.js:42:21)

After further digging, it seems to suggest that this version of node.js is too old for puppeteer and it needs at least version 14.3 (https://pprathameshmore.medium.com/top-level-await-support-in-node-js-v14-3-0-8af4f4a4d478).

**Comment by Disane87** [comment]
Thank you for this! Actually I'm refactoring the entire project to get rid of oclif and lift the entire project on new feet's to ensure further enhancements. I guess the new version will be available next year.
