### ISSUE TITLE
Amazon.com Error: No element found for selector: input[type=email]

### ISSUE THREAD

**Issue by timothevs** [Disane87/docudigger#935]
Version used: 2.0.6-dev.2 in Docker
Host: Ubuntu 22.04 LTS
TLD: .com

Using this via Docker - first run here's the debug log:-

```
[0] [debug] [2024-07-19 15:07:09] [scrape:amazon]: 	Options: {
[0]     "logLevel": "debug",
[0]     "debug": true,
[0]     "logPath": "logs",
[0]     "recurring": true,
[0]     "recurringCron": "*/30 * * * *",
[0]     "fileDestinationFolder": "data",
[0]     "fileFallbackExentension": ".pdf",
[0]     "onlyNew": false,
[0]     "username": "timg",
[0]     "password": "e",
[0]     "tld": "com",
[0]     "yearFilter": 2024,
[0]     "pageFilter": 1
[0] }
[0] [debug] [2024-07-19 15:07:09] [scrape:amazon]: 	Getting selectors...
[0] [debug] [2024-07-19 15:07:09] [scrape:amazon]: 	Selectors: {
[0]     "orderCards": "div.order.js-order-card",
[0]     "invoiceSpans": "span.hide-if-no-js .a-declarative[data-action=\"a-popover\"]",
[0]     "orderNr": ".yohtmlc-order-id span:nth-last-child(1) bdi",
[0]     "orderDate": ".a-column .a-row:nth-last-child(1) span",
[0]     "popover": "#a-popover-content-{{index}}",
[0]     "invoiceList": "ul.invoice-list",
[0]     "invoiceLinks": "a[href*=\"invoice.pdf\"]",
[0]     "pagination": "ul.a-pagination li.a-normal:nth-last-child(2) a",
[0]     "yearFilter": "select[name=\"timeFilter\"] option",
[0]     "authError": "#auth-error-message-box .a-unordered-list li",
[0]     "authWarning": "#auth-warning-message-box .a-unordered-list li",
[0]     "captchaImage": "div.cvf-captcha-img img[alt~=\"captcha\"]"
[0] }
[0]     Error: No element found for selector: input[type=email]
[0] docudigger scrape all exited with code 1
```

Thanks!

PS: real username/password removed/replaced.

**Comment by Disane87** [comment]
It seems amazon changed the login page and some of their DOM structure. Could you please retest this and, if thats not working, save the page (save as in the browser) and attach this?

It's pretty awkward to test different TLDs with amazon because you need an account and some orders and amazon is changing their site frequently to stop those scrappers. Unfortunatly they have different DOM structures across TLDs.

**Comment by Disane87** [comment]
Please try the latest version. There were several fixes. Hope it works for you with that new version.

**Comment by pavelz** [comment]
I have tried and got same error, it says image was built 9 months ago. 
```

[0] (node:15) Warning: SyntaxError
[0] module: @oclif/core@4.0.31
[0] task: findCommand (scrape:all.d)
[0] plugin: @disane-dev/docudigger
[0] root: /home/node/.npm-global/lib/node_modules/@disane-dev/docudigger
[0] message: Cannot use import statement outside a module
[0] See more details with DEBUG=*
[0] (Use `node --trace-warnings ...` to show where the warning was created)
[0] (node:15) Warning: SyntaxError
[0] module: @oclif/core@4.0.31
[0] task: findCommand (scrape:amazon:index.d)
[0] plugin: @disane-dev/docudigger
[0] root: /home/node/.npm-global/lib/node_modules/@disane-dev/docudigger
[0] message: Cannot use import statement outside a module
[0] See more details with DEBUG=*
[0] [info] [2025-08-04 21:08:29] [scrape:all]: 	runAll
[0] Platform:  linux
[0] [info] [2025-08-04 21:08:38] [scrape:amazon]: 	OnlyNew activated.
[0] [info] [2025-08-04 21:08:38] [scrape:amazon]: 	Getting last run
[0] [warn] [2025-08-04 21:08:38] [scrape:amazon]: 	process.json not found. Full run needed. OnlyNew deactivated.
[0] [info] [2025-08-04 21:08:38] [scrape:amazon]: 	Getting last run. Got: undefined
[0] [info] [2025-08-04 21:08:38] [scrape:amazon]: 	No latest scrape found. Processing all years and pages.
[0] [error] [2025-08-04 21:08:55] [scrape:all]: 	unhandledRejection: No element found for selector: input[type=email]
[0] Error: No element found for selector: input[type=email]
[0]     at assert (/home/node/.npm-global/lib/node_modules/@disane-dev/docudigger/node_modules/puppeteer-core/lib/cjs/puppeteer/util/assert.js:18:15)
[0]     at CdpFrame.type (/home/node/.npm-global/lib/node_modules/@disane-dev/docudigger/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Frame.js:871:40)
[0]     at async login (/home/node/.npm-global/lib/node_modules/@disane-dev/docudigger/dist/commands/scrape/amazon/helpers/auth.helper.js:31:9)
[0]     at async Amazon.run (/home/node/.npm-global/lib/node_modules/@disane-dev/docudigger/dist/commands/scrape/amazon/index.js:24:26)
[0]     at async Amazon._run (/home/node/.npm-global/lib/node_modules/@disane-dev/docudigger/node_modules/@oclif/core/lib/command.js:302:22)
[0]     at async Config.runCommand (/home/node/.npm-global/lib/node_modules/@disane-dev/docudigger/node_modules/@oclif/core/lib/config/config.js:425:25)
[0]     at async Promise.all (index 0)
[0]     at async All.run (/home/node/.npm-global/lib/node_modules/@disane-dev/docudigger/dist/commands/scrape/all.js:15:9)
[0]     at async All._run (/home/node/.npm-global/lib/node_modules/@disane-dev/docudigger/node_modules/@oclif/core/lib/command.js:302:22)
[0]     at async Config.runCommand (/home/node/.npm-global/lib/node_modules/@disane-dev/docudigger/node_modules/@oclif/core/lib/config/config.js:425:25)
[0] [error] [2025-08-04 21:08:56] [scrape:amazon]: 	unhandledRejection: No element found for selector: input[type=email]
[0] Error: No element found for selector: input[type=email]
[0]     at assert (/home/node/.npm-global/lib/node_modules/@disane-dev/docudigger/node_modules/puppeteer-core/lib/cjs/puppeteer/util/assert.js:18:15)
[0]     at CdpFrame.type (/home/node/.npm-global/lib/node_modules/@disane-dev/docudigger/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Frame.js:871:40)
[0]     at async login (/home/node/.npm-global/lib/node_modules/@disane-dev/docudigger/dist/commands/scrape/amazon/helpers/auth.helper.js:31:9)
[0]     at async Amazon.run (/home/node/.npm-global/lib/node_modules/@disane-dev/docudigger/dist/commands/scrape/amazon/index.js:24:26)
[0]     at async Amazon._run (/home/node/.npm-global/lib/node_modules/@disane-dev/docudigger/node_modules/@oclif/core/lib/command.js:302:22)
[0]     at async Config.runCommand (/home/node/.npm-global/lib/node_modules/@disane-dev/docudigger/node_modules/@oclif/core/lib/config/config.js:425:25)
[0]     at async Promise.all (index 0)
[0]     at async All.run (/home/node/.npm-global/lib/node_modules/@disane-dev/docudigger/dist/commands/scrape/all.js:15:9)
[0]     at async All._run (/home/node/.npm-global/lib/node_modules/@disane-dev/docudigger/node_modules/@oclif/core/lib/command.js:302:22)
[0]     at async Config.runCommand (/home/node/.npm-global/lib/node_modules/@disane-dev/docudigger/node_modules/@oclif/core/lib/config/config.js:425:25)
[0] docudigger scrape all exited with code 1
```
